#!/usr/bin/env bash
# =============================================================
# Zyphron — One-command production server setup
# Supports: Amazon Linux 2023, Ubuntu 22.04, Debian 12
#
# Usage:
#   DOMAIN=app.yourdomain.com \
#   RESEND_API_KEYS=re_... \
#   GROQ_API_KEYS=gsk_... \
#   bash scripts/setup-server.sh
# =============================================================
set -euo pipefail

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${BLUE}[zyphron]${NC} $*"; }
ok()   { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

# ─── Validate required vars ───────────────────────────────────
[[ -z "${DOMAIN:-}" ]]           && err "DOMAIN is required  →  export DOMAIN=app.yourdomain.com"
[[ -z "${RESEND_API_KEYS:-}" ]]  && warn "RESEND_API_KEYS not set — emails will be disabled"
[[ -z "${GROQ_API_KEYS:-}" ]]    && warn "GROQ_API_KEYS not set — AI features will be disabled"

log "Domain:  $DOMAIN"
log "Setting up Zyphron production server…"

# ─── Step 1: Install Docker ───────────────────────────────────
if ! command -v docker &>/dev/null; then
  log "Installing Docker…"
  if command -v dnf &>/dev/null; then
    # Amazon Linux 2023 / RHEL / Fedora
    sudo dnf install -y docker git curl openssl jq
    sudo systemctl start docker
    sudo systemctl enable docker
  elif command -v apt-get &>/dev/null; then
    # Ubuntu / Debian
    sudo apt-get update -qq
    sudo apt-get install -y -qq docker.io git curl openssl jq
    sudo systemctl start docker
    sudo systemctl enable docker
  else
    err "Unsupported OS — install Docker manually and re-run"
  fi
  sudo usermod -aG docker "$(whoami)"
  ok "Docker installed"
else
  ok "Docker already installed: $(docker --version)"
fi

# ─── Step 2: Install Docker Compose v2 ───────────────────────
if ! docker compose version &>/dev/null 2>&1; then
  log "Installing Docker Compose plugin…"
  COMPOSE_VERSION="v2.27.0"
  ARCH=$(uname -m); [[ "$ARCH" == "aarch64" ]] && ARCH="aarch64" || ARCH="x86_64"
  sudo mkdir -p /usr/local/lib/docker/cli-plugins
  sudo curl -sSL \
    "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-${ARCH}" \
    -o /usr/local/lib/docker/cli-plugins/docker-compose
  sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  ok "Docker Compose installed"
else
  ok "Docker Compose already installed: $(docker compose version --short)"
fi

# ─── Step 3: Generate secrets ─────────────────────────────────
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
ENCRYPTION_KEY="${ENCRYPTION_KEY:-$(openssl rand -hex 16)}"
PG_PASSWORD="${PG_PASSWORD:-$(openssl rand -hex 16)}"

ACME_EMAIL="${ACME_EMAIL:-admin@${DOMAIN}}"

# ─── Step 4: Write .env ───────────────────────────────────────
log "Writing .env.prod…"
cat > .env.prod << EOF
# Generated by setup-server.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
PG_PASSWORD=${PG_PASSWORD}

RESEND_API_KEYS=${RESEND_API_KEYS:-}
RESEND_FROM=Zyphron <noreply@${DOMAIN}>
GROQ_API_KEYS=${GROQ_API_KEYS:-}

REGISTRY_URL=localhost:5000
BOOTSTRAP_ADMIN_EMAILS=${BOOTSTRAP_ADMIN_EMAILS:-}
EOF
ok ".env.prod written"

# ─── Step 5: Create supporting config dirs ────────────────────
mkdir -p docker/traefik/letsencrypt
chmod 600 docker/traefik/letsencrypt 2>/dev/null || true

# Ensure Prometheus config exists
mkdir -p docker/prometheus
if [[ ! -f docker/prometheus/prometheus.yml ]]; then
  cat > docker/prometheus/prometheus.yml << 'PROM_EOF'
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zyphron-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
PROM_EOF
fi

# Ensure Loki config exists
mkdir -p docker/loki
if [[ ! -f docker/loki/loki.yml ]]; then
  cat > docker/loki/loki.yml << 'LOKI_EOF'
auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1m
  chunk_retain_period: 30s
schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  filesystem:
    directory: /loki/chunks
compactor:
  working_directory: /loki/boltdb-shipper-compactor
LOKI_EOF
fi

# ─── Step 6: Build Docker images ──────────────────────────────
log "Building Zyphron images (this takes 3–5 minutes)…"

# Re-exec as docker group if needed
if ! groups | grep -q docker; then
  warn "Re-executing with Docker group access…"
  exec sg docker "$0"
fi

# Build API
log "Building API image…"
docker build -t localhost:5000/zyphron-api:latest \
  --build-arg NODE_ENV=production \
  -f backend/Dockerfile \
  backend/
ok "API image built"

# Build Worker (reuses API image layers)
log "Building Worker image…"
docker build -t localhost:5000/zyphron-worker:latest \
  --build-arg NODE_ENV=production \
  -f backend/Dockerfile.worker \
  backend/ 2>/dev/null || \
docker build -t localhost:5000/zyphron-worker:latest \
  --build-arg TARGET=worker \
  -f backend/Dockerfile \
  backend/
ok "Worker image built"

# Build Frontend
log "Building Frontend image…"
docker build -t localhost:5000/zyphron-frontend:latest \
  --build-arg NEXT_PUBLIC_API_URL="https://api.${DOMAIN}" \
  --build-arg NEXT_PUBLIC_APP_URL="https://${DOMAIN}" \
  --build-arg NEXT_PUBLIC_GRAFANA_URL="https://${DOMAIN}/grafana" \
  -f frontend/Dockerfile \
  frontend/
ok "Frontend image built"

# Push to local registry
log "Pushing images to local registry…"
docker push localhost:5000/zyphron-api:latest
docker push localhost:5000/zyphron-worker:latest
docker push localhost:5000/zyphron-frontend:latest
ok "Images pushed"

# ─── Step 7: Run database migrations ─────────────────────────
log "Starting database…"
docker compose -f docker-compose.prod.yml --env-file .env.prod up -d postgres redis registry
sleep 10

log "Running database migrations…"
docker run --rm \
  --network zyphron_zyphron \
  -e DATABASE_URL="postgresql://zyphron:${PG_PASSWORD}@postgres:5432/zyphron?schema=public" \
  localhost:5000/zyphron-api:latest \
  npx prisma migrate deploy
ok "Migrations applied"

# ─── Step 8: Start all services ──────────────────────────────
log "Starting all Zyphron services…"
docker compose -f docker-compose.prod.yml --env-file .env.prod up -d
ok "All services started"

# ─── Step 9: Wait for health ──────────────────────────────────
log "Waiting for API to be healthy…"
for i in $(seq 1 30); do
  if curl -sf http://localhost:3000/api/v1/health &>/dev/null; then
    ok "API is healthy"
    break
  fi
  sleep 3
done

# ─── Done ─────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Zyphron is live! 🚀                          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BLUE}Dashboard:${NC}  https://app.${DOMAIN}"
echo -e "  ${BLUE}API:${NC}        https://api.${DOMAIN}/api/v1"
echo -e "  ${BLUE}Grafana:${NC}    https://app.${DOMAIN}/grafana  (no login)"
echo -e "  ${BLUE}Audit:${NC}      https://app.${DOMAIN}/audit"
echo ""
echo -e "  ${YELLOW}Saved to .env.prod — back this up!${NC}"
echo -e "  ${YELLOW}JWT Secret:${NC}        ${JWT_SECRET:0:16}…"
echo -e "  ${YELLOW}DB Password:${NC}       ${PG_PASSWORD:0:8}…"
echo ""
echo -e "  ${BLUE}CLI:${NC}"
echo -e "    npm install -g zyphron-cli"
echo -e "    zy login --api https://api.${DOMAIN}/api/v1"
echo ""
